/**
 * accretionDisk — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function accretionDisk() {
  return (
    <>
<svg  viewBox="0 0 700 300" role="img" aria-labelledby="bh-disk-title-accretionDisk bh-disk-desc-accretionDisk" xmlns="http://www.w3.org/2000/svg">
        <title id="bh-disk-title-accretionDisk">Accretion disk and relativistic jets</title>
        <desc id="bh-disk-desc-accretionDisk">Edge-on schematic of a black hole with a tilted accretion disk, polar jets launched along the rotation axis, the event horizon marked, and the ISCO marked at three times the Schwarzschild radius.</desc>
        <defs>
          <linearGradient id="disk-g-accretionDisk" x1="0" y1="0" x2="1" y2="0">
            <stop offset="0%" stop-color="currentColor" stop-opacity="0.15" />
            <stop offset="50%" stop-color="currentColor" stop-opacity="0.55" />
            <stop offset="100%" stop-color="currentColor" stop-opacity="0.15" />
          </linearGradient>
        </defs>

        {/* jets */}
        <path d="M 350 60 L 350 10" stroke="currentColor" stroke-width="7" opacity="0.5" stroke-linecap="round" />
        <path d="M 350 240 L 350 290" stroke="currentColor" stroke-width="7" opacity="0.5" stroke-linecap="round" />
        <path d="M 340 70 L 360 70" stroke="currentColor" stroke-width="2" />
        <text x="372" y="34" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">relativistic jet (⟂ disk)</text>

        {/* disk */}
        <ellipse cx="350" cy="150" rx="250" ry="52" fill={"url(#disk-g-accretionDisk)"} stroke="currentColor" stroke-width="1.5" opacity="0.9" />
        {/* ISCO */}
        <ellipse cx="350" cy="150" rx="96" ry="20" fill="none" stroke="currentColor" stroke-width="2" stroke-dasharray="7 5" />
        <text x="452" y="120" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">ISCO = 3rₛ</text>
        {/* horizon */}
        <ellipse cx="350" cy="150" rx="52" ry="52" fill="currentColor" opacity="0.85" />
        <text x="350" y="155" text-anchor="middle" font-size="11" font-family="monospace" fill="var(--bg, #fff)">BH</text>
        <text x="350" y="222" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">event horizon (rₛ)</text>
        <text x="70" y="272" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">Disk is hottest and brightest at the inner edge; friction, not the hole, does the radiating.</text>
      </svg>
    </>
  )
}
