/**
 * horizonCrossSection — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function horizonCrossSection() {
  return (
    <>
<svg  viewBox="0 0 700 300" role="img" aria-labelledby="bh-horizon-title-horizonCrossSection bh-horizon-desc-horizonCrossSection" xmlns="http://www.w3.org/2000/svg">
        <title id="bh-horizon-title-horizonCrossSection">Cross-section of a Schwarzschild black hole</title>
        <desc id="bh-horizon-desc-horizonCrossSection">Radial diagram showing the event horizon at the Schwarzschild radius, with the singularity drawn as a hatched central region and radial light rays bending inward as they approach.</desc>

        {/* light ray arrows (bent inward) */}
        <defs>
          <marker id="arr-k-horizonCrossSection" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="7" markerHeight="7" orient="auto-start-reverse">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" />
          </marker>
          <pattern id="hatch-k-horizonCrossSection" width="8" height="8" patternTransform="rotate(45)" patternUnits="userSpaceOnUse">
            <line x1="0" y1="0" x2="0" y2="8" stroke="currentColor" stroke-width="2" opacity="0.5" />
          </pattern>
        </defs>

        {/* singularity */}
        <circle cx="350" cy="150" r="54" fill={"url(#hatch-k-horizonCrossSection)"} stroke="currentColor" stroke-width="2.5" />
        <text x="350" y="155" text-anchor="middle" font-size="15" font-family="monospace" fill="currentColor">SINGULARITY</text>

        {/* event horizon */}
        <circle cx="350" cy="150" r="120" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="10 6" />
        <text x="350" y="52" text-anchor="middle" font-size="14" font-family="monospace" fill="currentColor">EVENT HORIZON  r = rₛ = 2GM/c²</text>

        {/* outer region marker */}
        <line x1="230" y1="150" x2="230" y2="252" stroke="currentColor" stroke-width="1.5" opacity="0.6" />
        <text x="230" y="270" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">rₛ</text>
        <line x1="350" y1="270" x2="350" y2="282" stroke="currentColor" stroke-width="1.5" opacity="0.6" />
        <text x="350" y="296" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">0</text>

        {/* infalling light rays, bent toward the hole */}
        <path d="M 90 60 Q 250 70 322 116" fill="none" stroke="currentColor" stroke-width="2" marker-end={"url(#arr-k-horizonCrossSection)"} opacity="0.8" />
        <path d="M 90 240 Q 250 230 322 184" fill="none" stroke="currentColor" stroke-width="2" marker-end={"url(#arr-k-horizonCrossSection)"} opacity="0.8" />
        <text x="96" y="46" font-size="12" font-family="monospace" fill="currentColor" opacity="0.8">infalling light — every path bends inward</text>
      </svg>
    </>
  )
}
