/**
 * lensing — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function lensing() {
  return (
    <>
<svg  viewBox="0 0 660 280" role="img" aria-labelledby="bh-lens-title-lensing bh-lens-desc-lensing" xmlns="http://www.w3.org/2000/svg">
        <title id="bh-lens-title-lensing">Gravitational lensing producing an Einstein ring</title>
        <desc id="bh-lens-desc-lensing">An observer, a distant lens, and a background source. Light from the source takes two paths around the lens, one above and one below, arriving at the same point on the sky and forming an Einstein ring.</desc>
        <defs>
          <marker id="arr-l-lensing" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" />
          </marker>
        </defs>

        {/* source */}
        <circle cx="600" cy="60" r="14" fill="currentColor" opacity="0.65" />
        <text x="600" y="40" text-anchor="middle" font-size="13" font-family="monospace" fill="currentColor">SOURCE</text>

        {/* lens */}
        <circle cx="300" cy="130" r="30" fill="none" stroke="currentColor" stroke-width="3" />
        <circle cx="300" cy="130" r="8" fill="currentColor" />
        <text x="300" y="180" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">LENS (M)</text>

        {/* observer */}
        <circle cx="40" cy="150" r="13" fill="currentColor" opacity="0.85" />
        <text x="40" y="185" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">OBSERVER</text>

        {/* two lensed paths */}
        <path d="M 300 116 Q 170 40 40 150" fill="none" stroke="currentColor" stroke-width="2" marker-end={"url(#arr-l-lensing)"} opacity="0.85" />
        <path d="M 300 144 Q 170 220 40 150" fill="none" stroke="currentColor" stroke-width="2" marker-end={"url(#arr-l-lensing)"} opacity="0.85" />
        <text x="150" y="248" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">α = 4GM/(c²b)</text>
      </svg>
    </>
  )
}
