/**
 * lightCone — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function lightCone() {
  return (
    <>
<svg  viewBox="0 0 660 330" role="img" aria-labelledby="tt-cone-title-lightCone tt-cone-desc-lightCone" xmlns="http://www.w3.org/2000/svg">
        <title id="tt-cone-title-lightCone">Light cone with timelike, null and spacelike worldlines</title>
        <desc id="tt-cone-desc-lightCone">A point in spacetime with its future light cone opening upward at 45 degrees. Inside the cone a steep timelike worldline, on the boundary a light ray at 45 degrees, and outside a shallow spacelike worldline that cannot be travelled by any massive object.</desc>
        <defs>
          <marker id="arr-c-lightCone" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" />
          </marker>
        </defs>

        {/* axes */}
        <line x1="60" y1="290" x2="620" y2="290" stroke="currentColor" stroke-width="2" />
        <line x1="60" y1="290" x2="60" y2="20" stroke="currentColor" stroke-width="2" />
        <text x="630" y="295" font-size="13" font-family="monospace" fill="currentColor">x</text>
        <text x="48" y="16" font-size="13" font-family="monospace" fill="currentColor">t</text>

        {/* light cone from event at (240,290) */}
        <line x1="240" y1="290" x2="240" y2="110" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-c-lightCone)"} />
        <line x1="240" y1="290" x2="420" y2="110" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-c-lightCone)"} />
        <line x1="240" y1="290" x2="60" y2="110" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-c-lightCone)"} />
        <circle cx="240" cy="290" r="7" fill="currentColor" />
        <text x="252" y="308" font-size="12" font-family="monospace" fill="currentColor">EVENT</text>

        {/* timelike: steep, stays inside */}
        <path d="M 240 290 Q 275 220 262 118" fill="none" stroke="currentColor" stroke-width="3" marker-end={"url(#arr-c-lightCone)"} />
        <text x="300" y="200" font-size="12" font-family="monospace" fill="currentColor">timelike</text>
        <text x="300" y="216" font-size="11" font-family="monospace" fill="currentColor" opacity="0.8">(v &lt; c) — you can ride it</text>

        {/* null label */}
        <text x="440" y="128" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">null boundary</text>

        {/* spacelike: shallow, outside */}
        <path d="M 240 290 Q 400 250 570 196" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="7 5" marker-end={"url(#arr-c-lightCone)"} />
        <text x="470" y="252" font-size="12" font-family="monospace" fill="currentColor">spacelike</text>
        <text x="470" y="268" font-size="11" font-family="monospace" fill="currentColor" opacity="0.8">(v &gt; c) — unreachable</text>

        <text x="60" y="320" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">Time travel means tracing a timelike path that arrives before it left.</text>
      </svg>
    </>
  )
}
