/**
 * penroseDiagram — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function penroseDiagram() {
  return (
    <>
<svg  viewBox="0 0 720 640" role="img" aria-labelledby="tt-penrose-title-penroseDiagram tt-penrose-desc-penroseDiagram" xmlns="http://www.w3.org/2000/svg">
        <title id="tt-penrose-title-penroseDiagram">Penrose conformal diagram of a Schwarzschild black hole</title>
        <desc id="tt-penrose-desc-penroseDiagram">A Kruskal-Szekeres conformal diagram. Null lines run at 45 degrees. The vertical event horizons divide the diagram into a left exterior region, a right exterior region, and two interior regions containing horizontal dashed spacelike singularities. The timelike infinities i-plus and i-minus and the null infinities scri-plus and scri-minus are marked, and the two exterior regions meet in a white-hole past singularity.</desc>
        <defs>
          <marker id="arr-p-penroseDiagram" viewBox="0 0 10 10" refX="9" refY="5" markerWidth="6" markerHeight="6" orient="auto">
            <path d="M 0 0 L 10 5 L 0 10 z" fill="currentColor" />
          </marker>
        </defs>

        <rect x="0" y="0" width="720" height="640" fill="none" />

        {/* ============ frame: 4 regions ============ */}
        {/* spacelike singularities: horizontal dashed, top of black hole, bottom of white hole */}
        <line x1="180" y1="170" x2="540" y2="170" stroke="currentColor" stroke-width="3" stroke-dasharray="12 7" />
        <text x="360" y="158" text-anchor="middle" font-size="13" font-family="monospace" fill="currentColor">FUTURE SINGULARITY  r = 0</text>
        <text x="360" y="192" text-anchor="middle" font-size="11" font-family="monospace" fill="currentColor" opacity="0.85">spacelike — the future is cut off here</text>

        <line x1="180" y1="470" x2="540" y2="470" stroke="currentColor" stroke-width="3" stroke-dasharray="12 7" />
        <text x="360" y="492" text-anchor="middle" font-size="13" font-family="monospace" fill="currentColor">PAST SINGULARITY  r = 0</text>
        <text x="360" y="508" text-anchor="middle" font-size="11" font-family="monospace" fill="currentColor" opacity="0.85">spacelike — this is a white hole</text>

        {/* event horizons: vertical at x=180 and x=540, from past to future singular. */}
        <line x1="180" y1="170" x2="180" y2="470" stroke="currentColor" stroke-width="3" />
        <line x1="540" y1="170" x2="540" y2="470" stroke="currentColor" stroke-width="3" />

        {/* i-  : past timelike infinity, mid-left and mid-right */}
        <text x="60" y="326" text-anchor="middle" font-size="14" font-family="monospace" fill="currentColor">ℐ⁻</text>
        <text x="660" y="326" text-anchor="middle" font-size="14" font-family="monospace" fill="currentColor">ℐ⁺</text>

        {/* scri: null infinities, the 45-degree outer edges */}
        <line x1="180" y1="470" x2="60" y2="350" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-p-penroseDiagram)"} opacity="0.9" />
        <line x1="60" y1="302" x2="180" y2="182" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-p-penroseDiagram)"} opacity="0.9" />
        <text x="52" y="330" text-anchor="end" font-size="13" font-family="monospace" fill="currentColor">ℐ⁰⁻</text>
        <text x="52" y="290" text-anchor="end" font-size="13" font-family="monospace" fill="currentColor">ℐ⁰⁺</text>

        <line x1="540" y1="470" x2="660" y2="350" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-p-penroseDiagram)"} opacity="0.9" />
        <line x1="660" y1="302" x2="540" y2="182" stroke="currentColor" stroke-width="2.5" marker-end={"url(#arr-p-penroseDiagram)"} opacity="0.9" />
        <text x="668" y="330" font-size="13" font-family="monospace" fill="currentColor">ℐ⁰⁻</text>
        <text x="668" y="290" font-size="13" font-family="monospace" fill="currentColor">ℐ⁰⁺</text>

        {/* future/past null infinity vertical extent label */}
        <text x="360" y="586" text-anchor="middle" font-size="13" font-family="monospace" fill="currentColor">∞   —   infinite spacetime compressed to finite paper</text>
        <text x="360" y="612" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">light rays compress to 45° lines; horizons are the vertical boundaries</text>

        {/* Radial null rays, drawn at 45 degrees inside the frame only. These mark
     the light paths that arrive at / depart from the bifurcation spheres, and
     must not be extended past the diagram's boundary. */}
        <line x1="180" y1="470" x2="240" y2="410" stroke="currentColor" stroke-width="1.4" opacity="0.45" />
        <line x1="540" y1="170" x2="600" y2="110" stroke="currentColor" stroke-width="1.4" opacity="0.45" />

        {/* region labels */}
        <text x="120" y="232" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">EXTERIOR</text>
        <text x="120" y="248" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">(our universe)</text>
        <text x="600" y="232" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">EXTERIOR</text>
        <text x="600" y="248" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">region II</text>
        <text x="360" y="252" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">BLACK HOLE (interior)</text>
        <text x="360" y="392" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">WHITE HOLE (interior)</text>

        {/* horizon labels */}
        <text x="188" y="500" font-size="11" font-family="monospace" fill="currentColor" opacity="0.9">event horizon</text>
        <text x="532" y="500" text-anchor="end" font-size="11" font-family="monospace" fill="currentColor" opacity="0.9">event horizon</text>

        {/* markers at top/bottom of the horizons = bifurcation points */}
        <circle cx="180" cy="170" r="5" fill="currentColor" />
        <circle cx="540" cy="170" r="5" fill="currentColor" />
        <circle cx="180" cy="470" r="5" fill="currentColor" />
        <circle cx="540" cy="470" r="5" fill="currentColor" />
      </svg>
    </>
  )
}
