/**
 * tidalStretch — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function tidalStretch() {
  return (
    <>
<svg  viewBox="0 0 640 260" role="img" aria-labelledby="bh-tidal-title-tidalStretch bh-tidal-desc-tidalStretch" xmlns="http://www.w3.org/2000/svg">
        <title id="bh-tidal-title-tidalStretch">Geodesic deviation showing tidal stretching</title>
        <desc id="bh-tidal-desc-tidalStretch">A small extended body drawn at three distances from a black hole. Far away its width matches its height. As it approaches the horizon the same object becomes progressively elongated along the radial direction and compressed sideways.</desc>

        <circle cx="540" cy="130" r="40" fill="currentColor" opacity="0.12" />
        <circle cx="540" cy="130" r="40" fill="none" stroke="currentColor" stroke-width="2.5" stroke-dasharray="6 5" />
        <text x="540" y="200" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">EVENT HORIZON</text>

        {/* far: round */}
        <g>
          <ellipse cx="120" cy="90" rx="22" ry="22" fill="none" stroke="currentColor" stroke-width="2.5" />
          <text x="120" y="140" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">far: r ≫ rₛ</text>
          <text x="120" y="158" text-anchor="middle" font-size="11" font-family="monospace" fill="currentColor" opacity="0.8">round, weak tides</text>
        </g>

        {/* middle: elongated */}
        <g>
          <ellipse cx="290" cy="90" rx="17" ry="32" fill="none" stroke="currentColor" stroke-width="2.5" />
          <text x="290" y="150" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">closer: tides</text>
          <text x="290" y="168" text-anchor="middle" font-size="11" font-family="monospace" fill="currentColor" opacity="0.8">elongating</text>
        </g>

        {/* near: spaghettified */}
        <g>
          <ellipse cx="440" cy="90" rx="10" ry="48" fill="none" stroke="currentColor" stroke-width="2.5" />
          <text x="440" y="170" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">near rₛ: spaghettified</text>
        </g>

        <line x1="70" y1="225" x2="600" y2="225" stroke="currentColor" stroke-width="1.5" opacity="0.5" />
        <text x="70" y="245" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">Δa ∝ 2GM Δx / r³ — tidal stretching scales as 1/r³, the mass factorises out</text>
      </svg>
    </>
  )
}
