/**
 * twinParadox — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function twinParadox() {
  return (
    <>
<svg  viewBox="0 0 560 320" role="img" aria-labelledby="tt-twin-title-twinParadox tt-twin-desc-twinParadox" xmlns="http://www.w3.org/2000/svg">
        <title id="tt-twin-title-twinParadox">Twin paradox spacetime diagram</title>
        <desc id="tt-twin-desc-twinParadox">A stay-at-home twin travels a straight vertical worldline while the traveller's worldline curves away and returns, meeting again. Light signals sent from the stay-at-home twin catch up to the traveller, showing the traveller's view being blue shifted near turnaround.</desc>

        <line x1="70" y1="280" x2="530" y2="280" stroke="currentColor" stroke-width="2" />
        <line x1="70" y1="280" x2="70" y2="20" stroke="currentColor" stroke-width="2" />
        <text x="540" y="285" font-size="13" font-family="monospace" fill="currentColor">x</text>
        <text x="58" y="16" font-size="13" font-family="monospace" fill="currentColor">t</text>

        {/* stay home: straight */}
        <line x1="140" y1="280" x2="140" y2="45" stroke="currentColor" stroke-width="3" />
        <text x="140" y="300" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">stay-at-home (worldline)</text>

        {/* traveller: out and back, kink at turnaround */}
        <path d="M 140 280 L 380 150 L 140 45" fill="none" stroke="currentColor" stroke-width="3" stroke-dasharray="9 5" />
        <text x="396" y="152" font-size="12" font-family="monospace" fill="currentColor">traveller (turnaround)</text>

        {/* reunion */}
        <circle cx="140" cy="280" r="8" fill="currentColor" />
        <circle cx="140" cy="45" r="8" fill="currentColor" />
        <text x="112" y="270" font-size="12" font-family="monospace" fill="currentColor">departure</text>
        <text x="96" y="34" text-anchor="end" font-size="12" font-family="monospace" fill="currentColor">reunion</text>

        <text x="70" y="318" font-size="12" font-family="monospace" fill="currentColor" opacity="0.85">The traveller's path is shorter, so ∫dτ is smaller — they are younger at reunion.</text>
      </svg>
    </>
  )
}
