/**
 * wormhole — lifted verbatim from the deployed static site.
 *
 * Geometry must not be "tidied": the Penrose diagram depends on null lines
 * at exactly 45 degrees and horizons exactly vertical. Generated by
 * scripts/generate_diagrams.py; edit that, not this file.
 */
export function wormhole() {
  return (
    <>
<svg  viewBox="0 0 640 240" role="img" aria-labelledby="tt-worm-title-wormhole tt-worm-desc-wormhole" xmlns="http://www.w3.org/2000/svg">
        <title id="tt-worm-title-wormhole">Morris-Thorne traversable wormhole throat</title>
        <desc id="tt-worm-desc-wormhole">A side-on embedding of a wormhole showing a flat exterior on the left, a throat pinching in the middle, and a second flat exterior on the right, with the time-shifting disks shown in cyan.</desc>
        <path d="M 40 200 L 180 200 C 240 200 280 130 320 130 C 360 130 400 200 460 200 L 600 200" fill="none" stroke="currentColor" stroke-width="3" />
        <text x="90" y="228" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">exterior A</text>
        <text x="320" y="112" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">throat</text>
        <text x="550" y="228" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor">exterior B</text>
        <circle cx="320" cy="130" r="4" fill="currentColor" />
        <text x="320" y="82" text-anchor="middle" font-size="12" font-family="monospace" fill="currentColor" opacity="0.9">time-shift disk</text>
        <text x="320" y="66" text-anchor="middle" font-size="11" font-family="monospace" fill="currentColor" opacity="0.85">Morris–Thorne: exotic matter holds it open</text>
      </svg>
    </>
  )
}
